[김기용] add: property, user, map, reservation 모델 생성완료
wecode-bootcamp-korea/14-2nd-AirBitAndByte-backend pull request #5
Opened 2020-12-02 08:42 UTC by amusesla

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 1차 모델링 models.py 작성완료
		 
## 수정 사항들 자세한 내용
- Property 모델 생성
- User 모델 생성
- Map 모델 생성
- Reservation 모델 생성

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2020-12-02 08:59 UTC, soheon-lee commented on property/models.py
> +    affordability = models.DecimalField(max_digits=11, decimal_places=3)
1점에서 5점 사이인 것 같은데 digit을 이만큼 주시나요?

2020-12-02 08:59 UTC, soheon-lee commented on property/models.py
> +    host    = models.ForeignKey('Host', on_delete=models.CASCADE)
리뷰가 달려있는 집의 집주인 말고도 다른 host들도 댓글을 달 수 있는건가요? host가 왜 필요한지 궁금합니다.

2020-12-02 08:59 UTC, soheon-lee commented on reservation/models.py
> +    host      = models.ForeignKey('property.Host', on_delete=models.CASCADE)
property가 숙소가 맞나요 혹시? property가 정해져있다면 host가 이미 있다는건데, 다시 host 를 붙인 필드가 있는 이유가 궁금합니다 :)

2020-12-02 09:20 UTC, amusesla commented on property/models.py
> +    affordability = models.DecimalField(max_digits=11, decimal_places=3)
수정하였습니다!

2020-12-02 11:31 UTC, amusesla commented on reservation/models.py
> +    host      = models.ForeignKey('property.Host', on_delete=models.CASCADE)
host 제거하였습니다!

2020-12-02 12:51 UTC, jamessoun93 requested changes

2020-12-02 12:51 UTC, jamessoun93 commented on map/models.py
> +    longitube  = models.DecimalField(max_digits=10, decimal_places=6)
`latitude`, `longitude` 로 오타 수정해주세요.

2020-12-02 12:51 UTC, jamessoun93 commented on map/models.py
> +    longitube  = models.DecimalField(max_digits=10, decimal_places=6)
마찬가지입니다.

2020-12-02 12:51 UTC, jamessoun93 commented on map/models.py
> +    longitube  = models.DecimalField(max_digits=10, decimal_places=6)
여기도 수정해주세요.

2020-12-02 12:51 UTC, jamessoun93 commented on map/models.py
> +    longitube  = models.DecimalField(max_digits=10, decimal_places=6)
여기도..ㅎㅎ

2020-12-02 12:51 UTC, jamessoun93 commented on map/models.py
> +    longitube  = models.DecimalField(max_digits=10, decimal_places=6)
여기또한..ㅎㅎ

2020-12-02 12:51 UTC, jamessoun93 commented on property/models.py
> +    attribute       = models.ManyToManyField('Attribute', through='PropertyAttribute')
M2M 필드는 컬럼명 복수형으로 선언해주세요.

2020-12-02 12:51 UTC, jamessoun93 commented on property/models.py
> +    facility        = models.ManyToManyField('Facility', through='PropertyFacility')
여기도 M2M 필드는 컬럼명 복수형으로 선언해주세요.

2020-12-02 12:51 UTC, jamessoun93 commented on reservation/models.py
> +    cvc         = models.CharField(max_length=200)
비밀번호보다 더 sensitive 한 정보라고 볼 수 있는 신용카드 정보를 이렇게 그대로 저장을 해놓는 것에 대해서 다시한번 생각해보셔야 할 것 같습니다.

2020-12-02 12:51 UTC, jamessoun93 commented on user/models.py
> +    email        = models.EmailField()
`email` 필드도 `max_length` 필요하겠죠?

2020-12-02 14:18 UTC, amusesla commented on map/models.py
> +    longitube  = models.DecimalField(max_digits=10, decimal_places=6)
수정했습니다!

2020-12-02 14:18 UTC, amusesla commented on map/models.py
> +    longitube  = models.DecimalField(max_digits=10, decimal_places=6)
수정했습니다!

2020-12-02 14:19 UTC, amusesla commented on map/models.py
> +    longitube  = models.DecimalField(max_digits=10, decimal_places=6)
수정했습니다....

2020-12-02 14:19 UTC, amusesla commented on map/models.py
> +    longitube  = models.DecimalField(max_digits=10, decimal_places=6)
수정했습니다.

2020-12-02 14:19 UTC, amusesla commented on map/models.py
> +    longitube  = models.DecimalField(max_digits=10, decimal_places=6)
수정했...습니다..

2020-12-02 14:26 UTC, amusesla commented on property/models.py
> +    attribute       = models.ManyToManyField('Attribute', through='PropertyAttribute')
M2M 필드 컬럼 복수형. 수정했습니다.

2020-12-02 14:26 UTC, amusesla commented on property/models.py
> +    facility        = models.ManyToManyField('Facility', through='PropertyFacility')
M2M 필드 컬럼이름 복수형. 수정했습니다.

2020-12-02 14:26 UTC, amusesla commented on user/models.py
> +    email        = models.EmailField()
맞습니다. 수정했습니다.

2020-12-03 01:45 UTC, amusesla commented on reservation/models.py
> +    cvc         = models.CharField(max_length=200)
I'mport 라이브러리 사용여부 프론트랑 상의하겠습니다.!

2020-12-03 06:02 UTC, merged