[김기용] RegisterView, LoginView, socialLogin, socialRegister
wecode-bootcamp-korea/14-2nd-AirBitAndByte-backend pull request #6
Opened 2020-12-04 02:04 UTC by amusesla

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 일반 로그인
- 일반 회원가입
- 소셜 로그인 & 회원가입
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- google social 부분에서 client_id 가 왜 필요한지 알고싶습니다.
https://developers.google.com/identity/sign-in/web/backend-auth
https://google-auth.readthedocs.io/en/latest/reference/google.oauth2.id_token.html#google.oauth2.id_token.verify_oauth2_token

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2020-12-04 06:16 UTC, jamessoun93 requested changes

2020-12-04 06:16 UTC, jamessoun93 commented on user/views.py
> +                    'isVerified': 'True'
- 이메일을 알려줘야하는 이유가 있을까요?
- 토큰자체를 verification 을 pass 했을때 주는거라 불필요한 정보라고 생각합니다.

2020-12-04 06:16 UTC, jamessoun93 commented on user/views.py
> +            return JsonResponse({'result':context}, status=200)
`get_or_create()` 를 사용하면 훨씬 더 보기좋게 리팩토링 하실 수 있습니다.

2020-12-04 07:25 UTC, amusesla commented on user/views.py
> +            return JsonResponse({'result':context}, status=200)
옙!

2020-12-04 07:25 UTC, amusesla commented on user/views.py
> +                    'isVerified': 'True'
예!

2020-12-07 04:53 UTC, jamessoun93 requested changes

2020-12-07 04:53 UTC, jamessoun93 commented on my_db.py
> +import os
my_db 파일 올라왔네요. 없애주세요!

2020-12-07 04:53 UTC, jamessoun93 commented on user/views.py
> +                return JsonResponse({'result':context}, status=200)
```suggestion
                return JsonResponse({'access_token': token}, status=200)
```
불필요한 nesting을 줄여주는게 프론트 입장에서 좋을 것 같네요.

2020-12-07 04:53 UTC, jamessoun93 commented on user/views.py
> +            print(data)
디버깅용 프린트문은 지워주세요~

2020-12-07 04:53 UTC, jamessoun93 commented on user/views.py
> +            if User.objects.filter(email=data['email']):
여기서는 존재여부만 파악해야하면 되기때문에 `.exists()`를 함께 사용해주시는게 좋습니다.

2020-12-07 04:53 UTC, jamessoun93 commented on user/views.py
> +            user =  User.objects.filter(email=data['email'])
여기서 filter 를 쓰시는 이유가 있을까요?

2020-12-07 04:53 UTC, jamessoun93 commented on user/views.py
> +                    'username': user[0].email
위에서 get 을 사용하시면 불필요한 index 접근이 필요없고 아래 Index 관련 익셉션도 필요없어지게 됩니다.

2020-12-08 08:00 UTC, jamessoun93 requested changes

2020-12-08 08:00 UTC, jamessoun93 commented on my_db.py
> +import os
@amusesla 이거 반영 안되었네요!

2020-12-08 08:00 UTC, jamessoun93 commented on reservation/views.py
> +        except KeyError:
- 만들어두신 availability 확인하는 유틸함수를 여기서 사용하셔야하지 않을까요?
- 현재로서는 무작정 예약이 가능하게끔 되어있네요.

2020-12-08 08:00 UTC, jamessoun93 commented on core/utils.py
> +def dateParser(date):
함수명 snake case로 변경해주세요!

2020-12-08 08:00 UTC, jamessoun93 commented on core/utils.py
> +def checkAvailability(property, check_in, check_out):
- 함수명 `snake_case`로 변경해주세요!
- 추가로, 유저가 입력한 `check_out` 값이 `check_in` 보다 이른 날짜인 경우를 거르는 `validation` 로직을 추가해주셔야할 것 같습니다.

2020-12-08 08:00 UTC, jamessoun93 commented on core/utils.py
> +#only works if date format(2020-02-06)
이런 조건도 해당 함수에 포함시켜주시면 더욱 완벽할 것 같습니다.

2020-12-08 08:00 UTC, jamessoun93 commented on core/utils.py
> +            avalilability.append(False)
```suggestion
            availability.append(True)
        else:
            availability.append(False)
```

2020-12-08 08:00 UTC, jamessoun93 commented on property/views.py
> +#                           Q(title__contains          =search))
불필요한 주석 없애주세요!

2020-12-08 08:00 UTC, jamessoun93 commented on property/views.py
> +            guest           = request.GET.get('guest', None)
이런 부분은 변수명과 파라미터명을 조금 더 명확하게 지어주셨으면 좋겠습니다. 실제로 인원 수를 뜻하는지 로직을 보고 파악해야해서요.

2020-12-08 08:00 UTC, jamessoun93 commented on property/views.py
> +                         review.affordability)/6) for review in property.review_set.all()],
혹시 이 부분 전체 리뷰 평균내려고 하시는게 아니고 리뷰별 평균 점수만 list 에 담는게 맞는건가요?

2020-12-08 08:00 UTC, jamessoun93 commented on property/views.py
> +            available_rooms=[]
지워주세요!

2020-12-08 08:00 UTC, jamessoun93 commented on property/views.py
> +            ]
이건 현재 쓰이는곳이 없는 것 같네요.

2020-12-08 08:00 UTC, jamessoun93 commented on property/views.py
> +            }
얘도 마찬가지구요.

2020-12-08 08:00 UTC, jamessoun93 commented on property/views.py
> +            properties = Property.objects.select_related('host').prefetch_related('review_set', 'facility', 'size','rule', 'review_set').filter(**conditions)
이 줄은 가독성 좋게 바꿔주세요~

2020-12-08 08:00 UTC, jamessoun93 commented on property/views.py
> +                    ],
여기도 바로 위 클래스에서 남겨드렸던 질문과 동일한 내용입니다.

2020-12-08 08:00 UTC, jamessoun93 commented on property/views.py
> +            }
메소드 내용 전체적으로 가독성 좋게 리팩토링해주세요.

2020-12-08 08:00 UTC, jamessoun93 commented on user/views.py
> +                return JsonResponse({'result':context}, status=200)
- 이것도 반영해주세요.

2020-12-08 08:00 UTC, jamessoun93 commented on user/views.py
> +            if User.objects.filter(email=data['email']):
- 이것도 반영해주세요.

2020-12-08 08:00 UTC, jamessoun93 commented on user/views.py
> +            user =  User.objects.filter(email=data['email'])
- 이것도 반영해주세요.

2020-12-08 09:00 UTC, amusesla commented on my_db.py
> +import os
git rm --cached -r my_db.py 적용해서 삭제하였습니다.

2020-12-08 09:02 UTC, amusesla commented on user/views.py
> +                return JsonResponse({'result':context}, status=200)
``` python
return JsonResponse({'accessToken':access_token}, status=200)

카멜케이스로 이번에 작성하기로 약속하여 이렇게 수정하였습니다.

2020-12-08 09:06 UTC, amusesla commented on user/views.py
> +            print(data)
삭제하였습니다.

2020-12-08 09:08 UTC, amusesla commented on user/views.py
> +            if User.objects.filter(email=data['email']):
```
if User.objects.filter(email=data['email']).exists():

수정하였습니다.

2020-12-08 09:10 UTC, amusesla commented on user/views.py
> +            user =  User.objects.filter(email=data['email'])
``` python
user = User.objects.get(email=data['email'])
```
수정하였습니다.!

2020-12-08 09:11 UTC, amusesla commented on user/views.py
> +                    'username': user[0].email
감사합니다!!

2020-12-08 09:28 UTC, amusesla commented on reservation/views.py
> +        except KeyError:
<img width="604" alt="Screen Shot 2020-12-08 at 6 26 11 PM" src="https://user-images.githubusercontent.com/70562840/101465099-deb70480-3982-11eb-984b-6ea32e67c901.png">


reservation app을 아직 올리던게 아니였는데 ㅜㅜ git으로 좀더 깔끔하게 올려보도록 신경쓰겠습니다!!!
체크인 날짜와 체크아웃 날짜가 같을경우, 예약과 비교해서 비어있는 날에만 예약이 가능하도록 작성해보았습니다.

2020-12-08 09:36 UTC, amusesla commented on core/utils.py
> +def dateParser(date):
date_parser, check_availability 로 변경 완료했습니다.

2020-12-08 09:53 UTC, amusesla commented on core/utils.py
> +def checkAvailability(property, check_in, check_out):
``` python
def validate_check_in_check_out_date(check_in, check_out):
    if check_out <= check_in:
        return False
    return True
```
날짜를 비교하여 boolean 값을 반환하는 함수를 만들었습니다.!

2020-12-08 10:04 UTC, amusesla commented on core/utils.py
> +#only works if date format(2020-02-06)
<img width="443" alt="Screen Shot 2020-12-08 at 7 04 02 PM" src="https://user-images.githubusercontent.com/70562840/101469471-255b2d80-3988-11eb-9ff6-0055002119cd.png">

정규표현식 사용하여 함수 만들었습니다.

2020-12-08 10:13 UTC, amusesla commented on core/utils.py
> +            avalilability.append(False)
오타 수정완료했습니다!

2020-12-08 10:15 UTC, amusesla commented on property/views.py
> +#                           Q(title__contains          =search))
넵!!!

2020-12-08 10:17 UTC, amusesla commented on property/views.py
> +            guest           = request.GET.get('guest', None)
number_of_guest로 변수명을 수정해주었습니다.

2020-12-08 10:17 UTC, amusesla commented on property/views.py
> +                         review.affordability)/6) for review in property.review_set.all()],
아직 리뷰평균을 annotate와 aggregate로 못해서 일단은 저렇게 해두었습니다. ..ㅜㅜㅜ

2020-12-08 10:19 UTC, amusesla commented on property/views.py
> +            available_rooms=[]
함수가 끝나기전에 리스트 초기화 한다고 무심코 적어넣었네요 ㅠㅠ 지우겠습니다.

2020-12-08 10:22 UTC, amusesla commented on property/views.py
> +            ]
네 현재코드에는 지워져있습니다 ㅜㅜ user 리뷰받는지 알았습니다 죄송합니다!!

2020-12-08 10:24 UTC, amusesla commented on property/views.py
> +            }
넵!

2020-12-08 10:35 UTC, amusesla commented on property/views.py
> +            properties = Property.objects.select_related('host').prefetch_related('review_set', 'facility', 'size','rule', 'review_set').filter(**conditions)
<img width="382" alt="Screen Shot 2020-12-08 at 7 34 54 PM" src="https://user-images.githubusercontent.com/70562840/101472837-74a35d00-398c-11eb-81fa-26a04bb14aae.png">
넵!

2020-12-08 10:36 UTC, amusesla commented on property/views.py
> +            }
이부분은 승현님의 조언이 필요할것 같습니다 어떤 방향으로 리팩토링을 해야하는지요 ?

2020-12-08 15:01 UTC, closed without merging